server:
  image: node:12
  command: >
    sh -c "npm i && npm run backend"
  working_dir: /app
  volumes:
    - .:/app
  environment:
    PORT: 3001
    CONNECTION_STRING_DEV: postgres://postgres:postgres@postgres/TEST_SM
    PGUSER: postgres
    PGHOST: postgres
    PGPASSWORD: postgres
    PGDATABASE: TEST_SM
  ports:
    - "3001:3001"
    - "5858:5858"
  links:
    - postgres
frontend:
  image: node:12
  command: >
    sh -c "cd frontend/js && npm i && npm run start"
  working_dir: /app/frontend/js
  volumes:
    - .:/app/frontend/js
  environment:
    PORT: 4000
  ports:
    - "4000:4000"
postgres:
  image: postgres
  hostname: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: TEST_SM
  volumes:
    - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    # - postgres-data:/var/lib/postgresql/data
  restart: unless-stopped

pgadmin:
  image: dpage/pgadmin4
  links:
    - postgres
  ports:
    - "8080:8080"
  environment:
    PGADMIN_DEFAULT_EMAIL: siraj.pathan@hotmail.com
    PGADMIN_DEFAULT_PASSWORD: 12345
    PGADMIN_LISTEN_PORT: 8080
# db:
#   image: mysql:5.7
#   ports:
#     - '3306:3306'
#   environment:
#     - MYSQL_ROOT_PASSWORD=pass
#     - MYSQL_DATABASE=db
#   volumes:
#     - ./data/mysql:/var/lib/mysql
# pg_admin:
#   image: dpage/pgadmin4
#   restart: always
#   ports:
#     - 8080:8080
#   environment:
#     PGADMIN_DEFAULT_EMAIL: siraj.pathan@hotmail.com
#     PGADMIN_DEFAULT_PASSWORD: 12345
#     PGADMIN_LISTEN_ADDRESS: 0.0.0.0
#     PGADMIN_LISTEN_PORT: 8080
